import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Listify Terms of Service — the rules and conditions for using our platform.",
};

export default function TermsPage() {
  return (
    <div className="py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <div className="mb-10">
          <p className="text-xs font-bold uppercase tracking-widest text-brown-400 mb-3">Legal</p>
          <h1 className="text-4xl font-bold text-white mb-3">Terms of Service</h1>
          <p className="text-navy-400 text-sm">Effective Date: June 4, 2026 · Last Updated: June 4, 2026</p>
        </div>

        <div className="prose prose-invert max-w-none space-y-8 text-navy-300 leading-relaxed">

          <section>
            <p>
              Please read these Terms of Service (&quot;Terms&quot;) carefully before using the Listify website and service
              (collectively, the &quot;Service&quot;) operated by Listify (&quot;Listify,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
              By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
            </p>
          </section>

          <Section title="1. Description of Service">
            <p>
              Listify is an AI-powered platform that helps real estate professionals generate MLS listing descriptions
              and related marketing copy. The Service uses third-party artificial intelligence technology to produce
              written content based on property details you provide.
            </p>
          </Section>

          <Section title="2. Eligibility">
            <p>
              You must be at least 18 years of age and capable of forming a binding legal contract to use this Service.
              By using the Service, you represent and warrant that you meet these requirements. The Service is intended
              for use by real estate professionals and is not directed at consumers seeking to purchase property.
            </p>
          </Section>

          <Section title="3. Accounts">
            <ul>
              <li>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.</li>
              <li>You agree to provide accurate, current, and complete information when creating your account.</li>
              <li>You must notify us immediately at the contact information below if you suspect any unauthorized use of your account.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these Terms or that we reasonably believe are being used fraudulently.</li>
            </ul>
          </Section>

          <Section title="4. Subscriptions and Billing">
            <ul>
              <li><strong className="text-white">Free Plan:</strong> Listify offers a free tier with limited usage (currently 3 generations per calendar month). Free plan limits are subject to change at our discretion with reasonable notice.</li>
              <li><strong className="text-white">Pro Plan:</strong> Paid subscriptions are billed monthly in advance. By subscribing, you authorize us to charge your payment method on a recurring basis until you cancel.</li>
              <li><strong className="text-white">Cancellation:</strong> You may cancel your subscription at any time through your Account Settings. Cancellation takes effect at the end of your current billing period. You will retain Pro access through the end of the paid period. We do not provide partial refunds for unused time.</li>
              <li><strong className="text-white">Price Changes:</strong> We reserve the right to change subscription pricing with at least 30 days&apos; advance notice. Continued use after a price change constitutes acceptance of the new pricing.</li>
              <li><strong className="text-white">Payment Processing:</strong> Payments are processed by Stripe, Inc. Your payment information is transmitted directly to Stripe and is never stored on Listify&apos;s servers. Stripe&apos;s terms and privacy policy govern the processing of your payment data.</li>
              <li><strong className="text-white">Failed Payments:</strong> If a payment fails, your account may be downgraded to the free tier until the payment issue is resolved.</li>
            </ul>
          </Section>

          <Section title="5. AI-Generated Content — Important Disclaimer">
            <p>
              The listing descriptions and other content generated by the Service are produced by artificial intelligence
              and are provided for informational and professional assistance purposes only. You acknowledge and agree that:
            </p>
            <ul>
              <li>AI-generated content may contain errors, inaccuracies, omissions, or language that is inappropriate for your specific listing or market.</li>
              <li><strong className="text-white">You are solely responsible for reviewing, editing, and approving all AI-generated content before publishing or distributing it in any MLS, marketing channel, or other medium.</strong></li>
              <li>Listify makes no warranty that AI-generated content is accurate, complete, suitable for MLS submission, or compliant with any applicable laws, regulations, MLS rules, or NAR Code of Ethics.</li>
              <li>The quality and accuracy of generated content depends heavily on the accuracy and completeness of the information you provide.</li>
              <li>AI models may occasionally produce outputs that are repetitive, generic, or fail to capture unique property characteristics.</li>
            </ul>
          </Section>

          <Section title="6. Fair Housing Act Compliance — Critical Disclaimer">
            <p>
              Listify includes a Fair Housing compliance scanning feature that automatically reviews AI-generated content
              for phrases that may violate the Fair Housing Act (42 U.S.C. § 3604 et seq.) and similar state and local laws.
              You acknowledge and agree that:
            </p>
            <ul>
              <li><strong className="text-white">The Fair Housing compliance scanner is an assistive tool only and does not constitute legal advice, and Listify is not a law firm.</strong></li>
              <li>The scanner may not identify all potentially problematic language, and it may flag language that is in fact compliant.</li>
              <li>You remain solely responsible for ensuring that all listing descriptions and marketing materials you publish comply with the Fair Housing Act, the Americans with Disabilities Act, and all applicable federal, state, and local fair housing laws and regulations.</li>
              <li>Listify expressly disclaims any liability for Fair Housing violations, fines, penalties, complaints, or legal proceedings arising from your use of AI-generated content, whether or not the compliance scanner flagged issues.</li>
              <li>If you have questions about Fair Housing compliance, consult a qualified real estate attorney or your state&apos;s Real Estate Commission.</li>
            </ul>
          </Section>

          <Section title="7. Acceptable Use">
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Violate any applicable federal, state, local, or international law or regulation, including but not limited to the Fair Housing Act, CAN-SPAM Act, or any MLS rules.</li>
              <li>Generate content that is fraudulent, deceptive, defamatory, obscene, or otherwise objectionable.</li>
              <li>Misrepresent property features, condition, or characteristics in any listing description you publish.</li>
              <li>Attempt to reverse-engineer, scrape, copy, or create derivative works of the Service.</li>
              <li>Use automated means to access the Service in a way that exceeds your subscription limits.</li>
              <li>Share, resell, or sublicense your account access to third parties.</li>
              <li>Interfere with or disrupt the integrity or performance of the Service or its infrastructure.</li>
            </ul>
          </Section>

          <Section title="8. Intellectual Property">
            <ul>
              <li><strong className="text-white">Your Content:</strong> You retain ownership of the property information you submit to generate listings. You grant Listify a limited, non-exclusive license to process your inputs solely for the purpose of providing the Service.</li>
              <li><strong className="text-white">Generated Content:</strong> Subject to your compliance with these Terms and payment of applicable fees, you own the listing descriptions generated for you and may use them for your real estate business purposes.</li>
              <li><strong className="text-white">Listify&apos;s IP:</strong> The Service, including its software, design, trademarks, and all underlying technology, is owned by Listify and protected by intellectual property laws. You may not copy, reproduce, or create derivative works from the Service itself.</li>
              <li><strong className="text-white">Feedback:</strong> If you provide us with feedback or suggestions, you grant us a perpetual, irrevocable, royalty-free license to use that feedback without obligation to you.</li>
            </ul>
          </Section>

          <Section title="9. Privacy">
            <p>
              Your use of the Service is also governed by our <Link href="/privacy" className="text-brown-400 hover:underline">Privacy Policy</Link>,
              which is incorporated into these Terms by reference. By using the Service, you consent to the collection
              and use of your information as described in the Privacy Policy.
            </p>
          </Section>

          <Section title="10. Third-Party Services">
            <p>
              The Service integrates with third-party providers including Anthropic (AI generation), Stripe (payment processing),
              and others. Your use of third-party services is subject to their respective terms of service and privacy policies.
              Listify is not responsible for the practices, availability, or content of third-party services.
            </p>
          </Section>

          <Section title="11. Disclaimers of Warranties">
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT,
              OR THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS. WE DO NOT WARRANT THAT
              AI-GENERATED CONTENT WILL BE ACCURATE, COMPLETE, LEGALLY COMPLIANT, OR SUITABLE FOR ANY PARTICULAR PURPOSE.
              YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK.
            </p>
          </Section>

          <Section title="12. Limitation of Liability">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL LISTIFY, ITS OWNERS, EMPLOYEES, AGENTS,
              OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES,
              INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, REVENUE, DATA, BUSINESS, OR GOODWILL, ARISING OUT OF OR IN
              CONNECTION WITH YOUR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p>
              IN NO EVENT SHALL LISTIFY&apos;S TOTAL CUMULATIVE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO
              THESE TERMS OR THE SERVICE EXCEED THE GREATER OF (A) THE TOTAL AMOUNT YOU PAID TO LISTIFY IN THE TWELVE (12)
              MONTHS PRECEDING THE CLAIM OR (B) ONE HUNDRED DOLLARS ($100.00).
            </p>
            <p>
              SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES,
              SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU IN FULL.
            </p>
          </Section>

          <Section title="13. Indemnification">
            <p>
              You agree to indemnify, defend, and hold harmless Listify and its owners, employees, and agents from and against
              any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&apos; fees)
              arising out of or relating to: (a) your use of the Service; (b) any listing descriptions or other content
              you publish that were generated using the Service; (c) your violation of these Terms; (d) your violation of
              any applicable law, including the Fair Housing Act; or (e) your infringement of any third-party rights.
            </p>
          </Section>

          <Section title="14. Termination">
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time, with or without cause
              and with or without notice, including for violations of these Terms. Upon termination, your right to use the
              Service ceases immediately. Sections 5, 6, 8, 11, 12, 13, and 16 survive termination.
            </p>
          </Section>

          <Section title="15. Modifications to the Service and Terms">
            <p>
              We reserve the right to modify, suspend, or discontinue the Service at any time with reasonable notice.
              We may update these Terms from time to time. If we make material changes, we will notify you by email or
              by posting a prominent notice on the Service. Your continued use of the Service after the effective date
              of updated Terms constitutes your acceptance of the changes.
            </p>
          </Section>

          <Section title="16. Governing Law and Dispute Resolution">
            <p>
              These Terms are governed by and construed in accordance with the laws of the United States and the state
              in which Listify operates, without regard to conflict of law principles. Any dispute arising from these
              Terms or your use of the Service shall first be attempted to be resolved through good-faith negotiation.
              If negotiation fails, disputes shall be resolved by binding arbitration under the rules of the American
              Arbitration Association, conducted on an individual basis. YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A
              CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.
            </p>
          </Section>

          <Section title="17. Miscellaneous">
            <ul>
              <li><strong className="text-white">Entire Agreement:</strong> These Terms, together with our Privacy Policy, constitute the entire agreement between you and Listify regarding the Service.</li>
              <li><strong className="text-white">Severability:</strong> If any provision of these Terms is found to be unenforceable, the remaining provisions will remain in full force and effect.</li>
              <li><strong className="text-white">No Waiver:</strong> Our failure to enforce any right or provision of these Terms does not constitute a waiver of that right or provision.</li>
              <li><strong className="text-white">Assignment:</strong> You may not assign your rights under these Terms without our prior written consent. We may assign our rights freely.</li>
            </ul>
          </Section>

          <Section title="18. Contact">
            <p>
              If you have questions about these Terms, please contact us at:{" "}
              <a href="mailto:support@listify-silk.vercel.app" className="text-brown-400 hover:underline">
                support@listify-silk.vercel.app
              </a>
            </p>
          </Section>

        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-bold text-white mb-3">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}
